// <auto-generated />
using System;
using Blitz.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blitz.Infrastructure.Migrations
{
    [DbContext(typeof(BlitzContext))]
    [Migration("20240406183553_RefactorCodeAndAddedBorrowerToTheSchema")]
    partial class RefactorCodeAndAddedBorrowerToTheSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Blitz.Domain.Entities.Borrower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("act_aut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("an_com")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bilanturi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bloc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cod_fiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("data_stare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detalii_adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("di")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("etaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_100")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_120")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_200")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_410")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_412")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_416")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_420")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_423")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_430")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_432")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_439")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_480")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_500")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_602")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_701")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_710")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_755")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imp_756")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jud_com")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("judet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nr_com")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sfarsit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("str")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Borrower");
                });

            modelBuilder.Entity("Blitz.Domain.Entities.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apartament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bloc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CifraDeAfaceriNetaRON2018")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CifraDeAfaceriNetaRON2019")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CifraDeAfaceriNetaRON2020")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CifraDeAfaceriNetaRON2021")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCAEN2018")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCAEN2019")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCAEN2020")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCAEN2021")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodFiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CotaDePiata2018")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CotaDePiata2019")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CotaDePiata2020")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CotaDePiata2021")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriereCodCAEN2018")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriereCodCAEN2019")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriereCodCAEN2020")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriereCodCAEN2021")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Judet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localitate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumarRegistrulComertului")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfitNetRON2018")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfitNetRON2019")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfitNetRON2020")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfitNetRON2021")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salariati2018")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salariati2019")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salariati2020")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salariati2021")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StareFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("Blitz.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("DocumentContent")
                        .HasColumnType("Varbinary(max)")
                        .HasColumnName("DocumentContent");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Document", (string)null);
                });

            modelBuilder.Entity("Blitz.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("IsAdmin");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
